### PR TITLE
feat: update public input hash computation

### PR DESCRIPTION
**Pull request by chokobole**
Since our prover code is bumped up to version based on scroll zkevm v0.3, the
public input hash computation is changed as follows.

The main changes are followings:

- The instance part of the `final pair` is represented using two values
  instead of one because the `bn256` curve cannot fully represent the result
  of the keccak 256 hash, which is a bytes32 value. By splitting it into two
  values, we can accommodate the complete representation of the hash result.
- In the process of obtaining a dummy transaction hash, we ended up
  using the zero address as the value for the `to` field.
- In the public input hash, the fields for `coinbase`, `difficulty`, and
  `chain ID` were omitted, while the fields for `block hash`, `parent hash`,
  and `withdrawals root` were included.

### CODE REVIEW

**Comment by chokobole** [comment]
cc @kroma-network/zkp

**Review by Pangssu — APPROVED** [review]
LGTM

**Comment by Pangssu** [comment]
Should the #48 PR be merged first?

**Comment by chokobole** [comment]
@Pangssu Nope! you can safely merge this!

File: packages/contracts/contracts/libraries/Hashing.sol [hunk 1]
```diff
@@ -198,7 +198,37 @@ library Hashing {
...
+        _raw[6] = _rlps.logsBloom;
+        _raw[7] = _rlps.difficulty;
+        _raw[8] = RLPWriter.writeUint(_publicInput.number);
+        _raw[9] = RLPWriter.writeUint(_publicInput.gasLimit);
+        _raw[10] = _rlps.gasUsed;
+        _raw[11] = RLPWriter.writeUint(_publicInput.timestamp);
+        _raw[12] = _rlps.extraData;
+        _raw[13] = _rlps.mixHash;
+        _raw[14] = _rlps.nonce;
+        _raw[15] = RLPWriter.writeUint(_publicInput.baseFee);
```
Comment (0xHansLee) [inline packages/contracts/contracts/libraries/Hashing.sol:227]: The order is changed as well. Is it required changes for generating proof?
I'm not familiar with the proof and public info things, but it would be good to give some hints for this change.

Comment (chokobole) [reply packages/contracts/contracts/libraries/Hashing.sol:227]: Please see https://github.com/scroll-tech/zkevm-circuits/blob/v0.3.0-hotfix1/zkevm-circuits/src/pi_circuit.rs#L101-L179

Comment (chokobole) [reply packages/contracts/contracts/libraries/Hashing.sol:227]: Here `num_l1_msgs` are removed as we don't need this.

**Review by 0xHansLee — APPROVED** [review]
LGTM

File: components/node/eth/output.go [hunk 2]
```diff
@@ -39,20 +39,24 @@ func (o *OutputResponse) ToPublicInput(ChainId *big.Int) (bindings.TypesPublicIn
...
 	return bindings.TypesPublicInput{
-		Coinbase:         o.NextBlock.Coinbase,
+		BlockHash:        o.NextBlockRef.Hash,
+		ParentHash:       o.BlockRef.ParentHash,
 		Timestamp:        o.NextBlock.Time,
 		Number:           o.NextBlock.Number.Uint64(),
-		Difficulty:       common.Big0,
 		GasLimit:         new(big.Int).SetUint64(o.NextBlock.GasLimit),
 		BaseFee:          o.NextBlock.BaseFee,
-		ChainId:          ChainId,
```
Comment (0xHansLee) [inline components/node/eth/output.go:53]: We don't need `ChainId` arg anymore :)

Comment (chokobole) [reply components/node/eth/output.go:53]: Thank you for noticing me :) I removed them!

**Review by 0xHansLee — APPROVED** [review]

File: components/node/eth/output.go [hunk 3]
```diff
@@ -35,24 +35,28 @@ func (o *OutputResponse) ToOutputRootProof() bindings.TypesOutputRootProof {
...
+		withdrawalsRoot = *o.NextBlock.WithdrawalsHash
+	}
 	txHashes := make([][32]byte, len(o.NextTransactions))
 	for i, tx := range o.NextTransactions {
 		txHashes[i] = tx.Hash()
 	}
 	return bindings.TypesPublicInput{
-		Coinbase:         o.NextBlock.Coinbase,
+		BlockHash:        o.NextBlockRef.Hash,
+		ParentHash:       o.BlockRef.ParentHash,
```
Comment (0xHansLee) [inline components/node/eth/output.go:52]: The `ParentHash` should be the current block hash, `o.BlockRef.Hash`.

Comment (chokobole) [reply components/node/eth/output.go]: Sorry about that! I fixed it

**Review by 0xHansLee — APPROVED** [review]
lgtm

File: packages/contracts/contracts/L1/Colosseum.sol [hunk 4]
```diff
@@ -74,18 +74,14 @@ contract Colosseum is Initializable, Semver {
...
      * @notice The dummy transaction hash. This is used to pad if the
      *         number of transactions is less than MAX_TXS. This is same as:
      *         unsignedTx = {
      *           nonce: 0,
      *           gasLimit: 0,
      *           gasPrice: 0,
+     *           to: address(0),
      *           value: 0,
      *           data: '0x',
      *           chainId: CHAIN_ID,
```
[the remark this answers is not in the document]
Comment (chokobole) [reply packages/contracts/contracts/L1/Colosseum.sol:87]: Yes we need. See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md

File: packages/contracts/contracts/L1/Colosseum.sol [hunk 5]
```diff
@@ -512,13 +506,13 @@ contract Colosseum is Initializable, Semver {
      * @param _srcOutputRootProof Proof of the source output root.
      * @param _publicInput        Ingredients to compute the public input used by ZK proof verification.
      * @param _rlps               Pre-encoded RLPs to compute the next block hash of the source output root proof.
-     * @param _instance           Public input of ZK circuit.
+     * @param _expected           Expected public input of ZK circuit.
```
[the remark this answers is not in the document]
Comment (chokobole) [reply packages/contracts/contracts/L1/Colosseum.sol:509]: In terms of `ZK circuit`, I think public input sounds more natural.

File: packages/contracts/contracts/libraries/Hashing.sol [hunk 6]
```diff
@@ -198,7 +198,37 @@ library Hashing {
...
+    }
+
+    /**
+     * @notice Hashes the various elements of a block header into a block hash(before shanghai).
      *
      * @param _publicInput Public input which should hash to a block hash.
      * @param _rlps        Pre-RLP encoded data which should hash to a block hash.
```
[the remark this answers is not in the document]
Comment (chokobole) [reply packages/contracts/contracts/libraries/Hashing.sol:234]: Existing optimism code uses the phrase.

https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/libraries/Hashing.sol#LL149C5-L171C6

But when I asked it to chatgpt 'Public input which should be hashed to a block hash. 랑 Public input which should hash to a block hash. Which one is more natural or correct?'. It replies like followings:

> Both sentences are grammatically correct, but "Public input which should be hashed to a block hash." sounds more natural and appropriate. In this sentence, "hashed" is used as a verb in the passive voice, which is commonly used when describing the action of applying a hash function to something. Additionally, the preposition "to" is used to indicate the destination or target of the hashing process. Therefore, the first sentence is the more natural and preferred choice.

**Comment by chokobole** [comment]
After rebasing, it gives me this error. This leads to a slight change to overcome this compilation error.

```
Compiler run failed
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> contracts/L1/Colosseum.sol:355:13:
    |
355 |             _outputRoot,
    |     
```

**Review by seolaoh — APPROVED** [review]
LGTM
